### ISSUE TITLE
Mechanic of rendering image on a card

### ISSUE THREAD

**Issue by Visssarion** [Visssarion/Memory-Card-Game#6]

**Comment by Visssarion** [comment]
Inside of [card.gd](https://github.com/Visssarion/Memory-Card-Game/blob/main/scripts/classes/card.gd).
In _ready() change imageof child $Image sprite class to image from card_data variable ([CardData class](https://github.com/Visssarion/Memory-Card-Game/blob/main/scripts/classes/card_data.gd))

**Comment by HaiKonofanDesu** [comment]
@Visssarion can you add me to the Project? (CatzumaGaming)

**Comment by Visssarion** [comment]
> @Visssarion can you add me to the Project? (CatzumaGaming)

Added. May have to create github team in the future.
